# Array en Python
## Introducción Array y Matriz
La matrices no son una estructura propia de Python, una matriz es una lista de listas que nosotros interpretamos desde el punto de vista matemático. Es decir,
la estructura m = `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]` nosotros la interpretamos como la matriz 3x3 cuya primera fila es (1,2,3) y cuya segunda fila es (4,5,6), pero esto no deja de ser una interpretación.

In [1]:
listaX = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
listaX

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
type(listaX)

list

**Matriz.** Una matriz de dimensiones $m\times n$ es una tabla formada por elementos dispuestos en $m$ filas y $n$ columnas de la forma

$$A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}\end{pmatrix}$$

Los elementos de la matriz se representan con doble subíndice, $a_{ij}$, donde el primero indica la fila a la que pertenece y, el segundo, la columna.

Entonces, la matriz que hemos definido anteriormente

escrita en forma de tabla sería: `matrix` $= \displaystyle\begin{pmatrix} 1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9\end{pmatrix}$

Para acceder a los elementos de una matriz en `Python`, utilizamos la sintaxis `[][]`, donde primero indicamos la fila y, a continuación, la columna

In [68]:
listaX[0][2]

3

In [69]:
listaX[1][1]

5

In [70]:
listaX[2][0]

7

## Array con `numpy`

Existe una forma más sencilla de trabajar con matrices y es gracias a la librería `numpy`. Para importarla, simplemente hay que ejecutar la siguiente línea de código.

In [2]:
import numpy as np

### Crear un array

Para crear un `ndarray` usamos el método `.array()`.

Lo podemos hacer a partir de una lista:

In [4]:
lista = [1, 2, 3, 4, 5]
a = np.array(lista)
print(a)

[1 2 3 4 5]


In [5]:
type(a)

numpy.ndarray

O bien, a partir de una tupla:

In [6]:
tupla = (1, 2, 3, 4, 5, 6, 7)
b = np.array(tupla)
print(b)

[1 2 3 4 5 6 7]


In [7]:
type(b)

numpy.ndarray

Vamos a trabajar con los datos listaX y creamos en array

In [8]:
x = np.array(listaX)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
type(x)

numpy.ndarray

In [10]:
# Numero de dimension matriz
x.ndim

2

In [19]:
# Determinar la fila y columna matriz
x.shape

(3, 3)

In [53]:
# Determinar la cantidad de datos
x.size

9

In [20]:
# Tipo de datos numerico
x.dtype

dtype('int32')

In [21]:
# Saber el tamaño de la matriz kb
x.itemsize

4

In [22]:
# Imprimir los datos
print("Numero de elementos: " + str(x.size))
print("Numero de dimension: " + str(x.ndim))
print("Numero fila y columna: " + str(x.shape))
print("Tipo de datos numerico: " + str(x.dtype))
print("Tamaño de la matriz kb: " + str(x.itemsize))

Numero de elementos: 9
Numero de dimension: 2
Numero fila y columna: (3, 3)
Tipo de datos numerico: int32
Tamaño de la matriz kb: 4


In [24]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
# Seleccionar fila
a = x[2,]
a.ndim

1

In [29]:
# Seleccionar un dato matriz
x[1,1]

5

In [4]:
# Crear una lista datos
y = np.arange(0,12,1)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
# Crear un array segun la lista
y1 = y.reshape((3,4))
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
type(y1)

numpy.ndarray